# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
# Stacks detected: cicd:github-actions:.github/workflows
version: 2.1
jobs:
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0
    environment:
      PACKAGE_VERSION: 1.3.<< pipeline.number >>
    steps:
      - checkout
      - run:
          name: Build
          command: |
            dotnet test tests
      - persist_to_workspace:
          root: ./
          paths:
            - "*"
workflows:
  example:
    jobs:
      - test
