# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
# Stacks detected: cicd:github-actions:.github/workflows
version: 2.1

# setup: true

# orbs:
#   continuation: circleci/continuation@0.1.2

orbs:
  my-orb:
    executors:
      al:
        docker:
          - image: alpine:latest
    commands:
      print-parameters-command:
        steps:
          - run:
              name: Print Pipeline Parameters
              command: |
                # Iterate through all environment variables and print their values
                for var in $(env); do
                  echo "${var}"
                done
    jobs:
      print-parameters:
        executor:
          name: al
        steps:
          - print-parameters-command

executors:
  pactfoundation:
    docker:
      - image: pactfoundation/pact-cli
        environment:
          PACT_BROKER_BASE_URL: https://beso.pactflow.io
          PACT_BROKER_TOKEN: a0txy_Q79oE5-EDUSMvr_g

jobs:
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0
    environment:
      PACKAGE_VERSION: 1.3.<< pipeline.number >>
    steps:
      - checkout
      - run:
          name: Test
          command: |
            dotnet test tests

  pactflow:
    executor: pactfoundation
    steps:
      - run:
          name: canideploy
          command: |
            PACT_CLI="pact broker can-i-deploy --pacticipant pactflow-example-provider --version ${CIRCLE_SHA1} --to-environment production"
            ${PACT_CLI}
      - run:
          command: |
            echo << pipeline.trigger_source >>
            echo << pipeline.trigger_parameters.circleci.trigger_type >>
  # print-parameters:
  #   docker:
  #     - image: alpine:latest
  #   steps:
  #     - run:
  #         name: Print Pipeline Parameters
  #         command: |
  #           # Iterate through all environment variables and print their values
  #           for var in $(env); do
  #             echo "${var}"
  #           done



workflows:
  example:
    jobs:
      - my-orb/print-parameters
      - test:
          name: tests
      - pactflow:
          name: pact
          requires:
            - tests
