# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
# Stacks detected: cicd:github-actions:.github/workflows
version: 2.1

executors:
  pactfoundation:
    docker:
      - image: pactfoundation/pact-cli
        environment:
          PACT_BROKER_BASE_URL: https://beso.pactflow.io
          PACT_BROKER_TOKEN: a0txy_Q79oE5-EDUSMvr_g

jobs:
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0
    environment:
      PACKAGE_VERSION: 1.3.<< pipeline.number >>
    steps:
      - checkout
      - run:
          name: Test
          command: |
            dotnet test tests
      # - persist_to_workspace:
      #     root: ./
      #     paths:
      #       - "*"
      # - run:
      #     name: pact
      #     command: |
      #       bash .circleci/canideploy.sh providerdotnet

  pactflow:
    executor: pactfoundation
    steps:
      - run:
          name: canideploy
          command: |
            PACT_CLI="pact broker can-i-deploy --pacticipant pactflow-example-provider --version ${CIRCLE_SHA1} --to-environment production"
            ${PACT_CLI}

  # pactflow:
  #   executor: pactfoundation
  #   steps:
  #     - run:
  #         name: canideploy
  #         command: |
  #           .circleci/canideploy.sh pactflow-example-provider

  # copy:
  #   docker:
  #     - image: mcr.microsoft.com/dotnet/sdk:8.0
  #     - image: pactfoundation/pact-cli
  #   steps:
  #     - run:
  #         name: Copy files between containers
  #         command: |
  #           # Identify the source and destination container IDs
  #           source_container_id=$(docker ps -aqf "ancestor=source_image")
  #           destination_container_id=$(docker ps -aqf "ancestor=destination_image")
            
  #           # Copy files from source container to destination container
  #           docker cp $source_container_id:/path/to/source/file $destination_container_id:/path/to/destination/


workflows:
  example:
    jobs:
      - test:
          name: tests
      # - copy:
      #     name: copy
      #     requires:
      #       - tests
      - pactflow:
          name: pact
          requires:
            - tests
