# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
# Stacks detected: cicd:github-actions:.github/workflows
version: 2.1

executors:
  pactfoundation:
    docker:
      - image: pactfoundation/pact-cli
        environment:
          PACT_BROKER_BASE_URL: https://beso.pactflow.io
          PACT_BROKER_TOKEN: a0txy_Q79oE5-EDUSMvr_g

jobs:
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0
    environment:
      PACKAGE_VERSION: 1.3.<< pipeline.number >>
    steps:
      - checkout
      - run:
          name: Test
          command: |
            dotnet test tests

  pactflow:
    executor: pactfoundation
    steps:
      - run:
          name: canideploy
          command: |
            PACT_CLI="pact broker can-i-deploy --pacticipant pactflow-example-provider --version ${CIRCLE_SHA1} --to-environment production"
            ${PACT_CLI}
  print-parameters:
    parameters:
      body:
        default: "nothing"
        type: string
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Print Pipeline Parameters
          command: |
            # Iterate through all environment variables and print their values
            for var in $(env); do
              echo "${var}"
            done
            echo 'This is pipeline ID  parameters.body '

workflows:
  example:
    jobs:
      - print-parameters:
          when: 
            condition: << pipeline.trigger_parameters.webhook.body >>
      # - test:
      #     name: tests
      # - pactflow:
      #     name: pact
      #     requires:
      #       - tests
