# jobs:
#   print-parameters:
#     docker:
#       - image: alpine:latest
#     steps:
#       - run:
#           name: Print Pipeline Parameters
#           command: |
#             # Iterate through all environment variables and print their values
#             for var in $(env); do
#               echo "${var}"
#             done
# pipeline.number

workflows:
  normaltrigger:
    jobs:
      - my-orb/print-parameters
      - my-orb/test:
          name: tests
          buildnumber: "132456"
      - my-orb/pact-can-i-deploy:
          name: pact-can-i-deploy
          requires:
            - tests
      - my-orb/pact-deploy:
          name: pact-deploy
          requires:
            - pact-can-i-deploy