jobs:
  print-parameters:
    parameters:
      body:
        default: "nothing"
        type: string
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: Print Pipeline Parameters
          command: |
            # Iterate through all environment variables and print their values
            for var in $(env); do
              echo "${var}"
            done
            body='<< parameters.body >>'
            echo 'This is pipeline ID << parameters.body >>'
            pact_url=$(echo "${{ body }}" | jq -r '.event_type')
            echo "Extracted pact URL: $pact_url"
            echo "export PACT_URL=$pact_url" >> $BASH_ENV
  downstream-job:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Use extracted pact URL
          command: |
            echo "Pact URL: $PACT_URL"

workflows:
  webhooktrigger:
    jobs:
      - print-parameters:
          body: << pipeline.trigger_parameters.webhook.body >>
      - my-orb/test:
          name: tests
          buildnumber: "132456"
      - my-orb/pactflow:
          name: pact
          requires:
            - tests