jobs:
  print-parameters:
    parameters:
      body:
        default: "nothing"
        type: string
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Print Pipeline Parameters
          command: |
            # Iterate through all environment variables and print their values
            for var in $(env); do
              echo "${var}"
            done
            echo 'This is pipeline ID << parameters.body >>'

workflows:
  exampletrigger:
    jobs:
      - print-parameters:
          body: << pipeline.trigger_parameters.webhook.body >>
      - test:
          name: tests
      - pactflow:
          name: pact
          requires:
            - tests